# build
FROM golang:1.23-alpine AS builder

RUN apk add --no-cache \
    clang \
    curl \
    git \
    wget \
    vim \
    gcc \
    make \
    musl musl-dev \
    ncurses ncurses-dev ncurses-libs ncurses-static golangci-lint
    
ENV PATH=${PATH}:/usr/local/go/bin

WORKDIR  /opt/workspace/yc-360-script

ENTRYPOINT ["/bin/sh"]
