version: "1"
options:
  k: Lunar@9e8d7840-91e6-48a5-9f16-2a75b2b2fcf4
  j: C:\Program Files\Java\jdk1.8.0_121
  s: http://localhost:8080
  port: 8085
  address: 0.0.0.0
  processTokens:
   - buggyApp
  